### ISSUE TITLE
Mapa mental 

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-1-mapa-mental-irvinjs22620075#1]
![INVESTIGACION DOCUMENTAL M4PA MENTAL](https://user-images.githubusercontent.com/112287287/187813716-22ab7282-df70-42a1-849d-4d8e6f83ef41.jpeg)

**Comment by 11042002** [comment]
Tu calificación es de: 19.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
